"""init schema clean

Revision ID: 0dd7de0ba45c
Revises: 
Create Date: 2025-10-03 19:40:47.261865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dd7de0ba45c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('addr_road', sa.Text(), nullable=True),
    sa.Column('addr_jibun', sa.Text(), nullable=True),
    sa.Column('gu', sa.Text(), nullable=True),
    sa.Column('dong', sa.Text(), nullable=True),
    sa.Column('year_approved', sa.Integer(), nullable=True),
    sa.Column('xcrd', sa.Numeric(), nullable=True),
    sa.Column('ycrd', sa.Numeric(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.Column('use_yn', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_apartments_source_sourceid')
    )
    op.create_index('idx_apartments_gu_dong', 'apartments', ['gu', 'dong'], unique=False)
    op.create_index('idx_apartments_lat_lng', 'apartments', ['lat', 'lng'], unique=False)
    op.create_table('seoul_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gu', sa.String(length=20), nullable=False),
    sa.Column('dong', sa.String(length=30), nullable=True),
    sa.Column('complex', sa.String(length=80), nullable=True),
    sa.Column('lot_number', sa.String(length=20), nullable=True),
    sa.Column('building_use', sa.String(length=20), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('price_krw', sa.Integer(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('declare_type', sa.String(length=20), nullable=True),
    sa.Column('opr_sgg', sa.String(length=30), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gu', 'dong', 'complex', 'lot_number', 'area_m2', 'contract_date', 'price_krw', name='uq_trade_identity')
    )
    op.create_index(op.f('ix_seoul_trades_area_m2'), 'seoul_trades', ['area_m2'], unique=False)
    op.create_index(op.f('ix_seoul_trades_complex'), 'seoul_trades', ['complex'], unique=False)
    op.create_index(op.f('ix_seoul_trades_contract_date'), 'seoul_trades', ['contract_date'], unique=False)
    op.create_index(op.f('ix_seoul_trades_dong'), 'seoul_trades', ['dong'], unique=False)
    op.create_index(op.f('ix_seoul_trades_gu'), 'seoul_trades', ['gu'], unique=False)
    op.create_index(op.f('ix_seoul_trades_lat'), 'seoul_trades', ['lat'], unique=False)
    op.create_index(op.f('ix_seoul_trades_lng'), 'seoul_trades', ['lng'], unique=False)
    op.create_index(op.f('ix_seoul_trades_price_krw'), 'seoul_trades', ['price_krw'], unique=False)
    op.create_index(op.f('ix_seoul_trades_report_year'), 'seoul_trades', ['report_year'], unique=False)
    op.create_index('ix_trade_geo', 'seoul_trades', ['lat', 'lng'], unique=False)
    op.create_index('ix_trade_period', 'seoul_trades', ['gu', 'contract_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_period', table_name='seoul_trades')
    op.drop_index('ix_trade_geo', table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_report_year'), table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_price_krw'), table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_lng'), table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_lat'), table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_gu'), table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_dong'), table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_contract_date'), table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_complex'), table_name='seoul_trades')
    op.drop_index(op.f('ix_seoul_trades_area_m2'), table_name='seoul_trades')
    op.drop_table('seoul_trades')
    op.drop_index('idx_apartments_lat_lng', table_name='apartments')
    op.drop_index('idx_apartments_gu_dong', table_name='apartments')
    op.drop_table('apartments')
    # ### end Alembic commands ###
