"""Init apartments with x_y

Revision ID: 4f445e963307
Revises: 
Create Date: 2025-05-25 16:52:27.614726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f445e963307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apt_code', sa.String(), nullable=True),
    sa.Column('apt_name', sa.String(), nullable=True),
    sa.Column('total_households', sa.Integer(), nullable=True),
    sa.Column('size_range', sa.String(), nullable=True),
    sa.Column('old_address', sa.String(), nullable=True),
    sa.Column('new_address', sa.String(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apartments_apt_code'), ['apt_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_apartments_id'), ['id'], unique=False)

    op.create_table('household_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apt_code', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('is_owner_residing', sa.Boolean(), nullable=True),
    sa.Column('is_rented', sa.Boolean(), nullable=True),
    sa.Column('is_vacant', sa.Boolean(), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('household_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_status_apt_code'), ['apt_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_status_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_status_size'), ['size'], unique=False)

    op.create_table('rental_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apt_code', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('rent_price', sa.Integer(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rental_contract_apt_code'), ['apt_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_rental_contract_id'), ['id'], unique=False)

    op.create_table('sale_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apt_code', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_record_apt_code'), ['apt_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_record_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_record_id'))
        batch_op.drop_index(batch_op.f('ix_sale_record_apt_code'))

    op.drop_table('sale_record')
    with op.batch_alter_table('rental_contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rental_contract_id'))
        batch_op.drop_index(batch_op.f('ix_rental_contract_apt_code'))

    op.drop_table('rental_contract')
    with op.batch_alter_table('household_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_status_size'))
        batch_op.drop_index(batch_op.f('ix_household_status_id'))
        batch_op.drop_index(batch_op.f('ix_household_status_apt_code'))

    op.drop_table('household_status')
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apartments_id'))
        batch_op.drop_index(batch_op.f('ix_apartments_apt_code'))

    op.drop_table('apartments')
    # ### end Alembic commands ###
