name: Database Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install alembic

    - name: Run Alembic migration on SQLite DB
      run: |
        export PYTHONPATH=.
        export DATABASE_URL=sqlite:///./app/db/homesweethome.db
        alembic upgrade head

    - name: Check DB file after migration
      run: ls -al app/db

    - name: Run seed.py to populate SQLite DB
      run: |
        export PYTHONPATH=.
        export DATABASE_URL=sqlite:///./app/db/homesweethome.db
        python app/seed.py

    - name: Commit migration or data change if needed
      run: |
        git config --global user.email "somliboy@gmail.com"
        git config --global user.name "jaeyoung"
        git add -A
        git commit -m "Apply migration and seed data to SQLite DB" || echo "No changes to commit"
        git push || echo "Nothing to push"
